### ISSUE TITLE
Failed to create a bucket when running s3-create.py due to unsupported authorization mechanism

### ISSUE THREAD

**Issue by itsallvoodoo** [validatedpatterns/utilities#89]
Error is below:

[chad@bastion aws-tools]$ python s3-create.py -b voodoo-rh-bucket -r us-east-2 -p
Creating S3 Bucket:  voodoo-rh-bucket
Target S3 Bucket Region:  us-east-2
WARNING: S3 Bucket will be made public.
Could not create bucket [voodoo-rh-bucket]
An error occurred (InvalidRequest) when calling the PutBucketPolicy operation: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
Traceback (most recent call last):
  File "/var/code/utilities/aws-tools/s3-create.py", line 218, in <module>
    main()
  File "/var/code/utilities/aws-tools/s3-create.py", line 211, in main
    result = create_bucket(s3, bucket, region, public)
  File "/var/code/utilities/aws-tools/s3-create.py", line 119, in create_bucket
    myresult=getS3Client(region).put_bucket_policy(Bucket=bucket_name, Policy=bucket_policy)
  File "/home/chad/.local/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/chad/.local/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidRequest) when calling the PutBucketPolicy operation: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

It looks as if the encryption method that was in use is no longer supported by AWS. I'm not a python developer but it appears that the signature version must be v4. The version used by boto is s3:

74: config=botocore.client.Config(signature_version = 's3'))

**Comment by mbaldessari** [comment]
Thanks! @claudiol can you take a look? I suspect that all is needed is this:
```
diff --git a/aws-tools/s3-create.py b/aws-tools/s3-create.py
index 28ab82b..c256260 100644
--- a/aws-tools/s3-create.py
+++ b/aws-tools/s3-create.py
@@ -71,7 +71,7 @@ def getS3Client(region):
                           aws_access_key_id = aws_access_key_id,
                           aws_secret_access_key = aws_secret_access_key,
                           region_name = region,
-                          config=botocore.client.Config(signature_version = 's3'))
+                          config=botocore.client.Config(signature_version = 's3v4'))
         return s3
     except ClientError:
         print("Could not retrieve S3 client")
```

At least if my reading of https://www.github.com/boto/botocore/issues/2109 is correct

**Comment by claudiol** [comment]
@itsallvoodoo Fixed in: https://github.com/validatedpatterns/utilities/pull/95. Merging
